### ISSUE TITLE
Go lang Error While Editing Weird Things.

### ISSUE THREAD

**Issue by StarkGang** [jacobtomlinson/go-container-action#3]
Code : 
```
name: Sed
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'await event.edit('
          replace: 'await tr(event, '
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Test Translator'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: StarkGang
          commit_user_email: starkgangz@gmail.com
          commit_author: StarkGang <starkgangz@gmail.com>
```

Error:
```
panic: regexp: Compile(`await event.edit(`): error parsing regexp: missing closing ): `await event.edit(`

goroutine 1 [running]:
regexp.MustCompile(0xc0000160eb, 0x11, 0xc0001fe000)
	/usr/local/go/src/regexp/regexp.go:311 +0x152
main.findAndReplace(0xc000018960, 0xa, 0xc0000160eb, 0x11, 0xc00001616e, 0x10, 0x200, 0x0, 0x0)
	/app/main.go:43 +0x10b
main.main()
	/app/main.go:68 +0x22a
```
